export const committeeData = [
  {
    no: 1,
    name: "SangYong Han",
    affiliation: "Kookmin Univ.",
    email: "syhan@kookmin.ac.kr",
    position: "Chair",
  },
  {
    no: 2,
    name: "ShinTaek Kim",
    affiliation: "Daelim Univ. Prof.",
    email: "stkim@daelim.ac.kr",
    position: "Co-chair",
  },
  {
    no: 3,
    name: "Han Ko",
    affiliation: "Midwest Univ. Prof., CEO USAKO Group",
    email: "ceo@usakogroup.com",
    position: "Co-chair",
  },
  {
    no: 4,
    name: "JahngHyon Park",
    affiliation: "Hanyang Univ. Prof.",
    email: "jpark@hanyang.ac.kr",
    position: "Member of Committee",
  },
  {
    no: 5,
    name: "JaeKweon Han",
    affiliation: "Hanyang Univ. Prof.",
    email: "jkhan@hanyang.ac.kr",
    position: "Member of Committee",
  },
  {
    no: 6,
    name: "BaekKyu Cho",
    affiliation: "Kookmin Univ.Prof.",
    email: "BaekKyuCho@kookmin.ac.kr",
    position: "Member of Committee",
  },
  {
    no: 7,
    name: "SunYoung Kim",
    affiliation: "Kookmin Univ. Prof.",
    email: "sykim@kookmin.ac.kr",
    position: "Member of Committee",
  },
  {
    no: 8,
    name: "Hak Lee",
    affiliation: "Kyungpook Nati' Univ. Prof.",
    email: "yihak@knu.ac.kr",
    position: "Member of Committee",
  },
  {
    no: 9,
    name: "SungHo Kim",
    affiliation: "Yeungnam Univ. Prof.",
    email: "sunghokim@ynu.ac.kr",
    position: "Member of Committee",
  },
  {
    no: 10,
    name: "SangBae Park",
    affiliation: "Korea Polytechnics. Prof.",
    email: "sb810park@kopo.ac.kr",
    position: "Member of Committee",
  },
  {
    no: 11,
    name: "JooHyung Lee",
    affiliation: "ADD. Senior Researcher",
    email: "addlh77@gmail.com",
    position: "Member of Committee",
  },
  {
    no: 12,
    name: "YoungHo Choi",
    affiliation: "Korea Institute of Robot & Convergence. PhD",
    email: "rockboy@kiro.re.kr",
    position: "Member of Committee",
  },
  {
    no: 13,
    name: "DongHee Han",
    affiliation: "RideFlux.",
    email: "dhhan@rideflux.com",
    position: "Member of Committee",
  },
];
